spring.application.name=enrollment-service
server.port=8003

# gRPC Client Configuration
grpc.client.user-service.address=static://user-service:5000
grpc.client.user-service.negotiation-type=plaintext
grpc.client.course-service.address=static://course-service:5002
grpc.client.course-service.negotiation-type=plaintext
