services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_SECRET=c2VjcmV0LWtleS1tdXN0LWJlLWF0LWxlYXN0LTMtY2hhcmFjdGVycy1sb25nLWFuZC1iYXNlNjQtZW5jb2RlZA==
    ports:
      - "8001:8001"
    networks:
      - internal

networks:
  internal:
    external: true
    name: internal
