spring.application.name=assignment-service
server.port=8004

# gRPC Client Configuration
grpc.client.user-service.address=static://user-service:5000
grpc.client.user-service.negotiation-type=plaintext
grpc.client.course-service.address=static://course-service:5002
grpc.client.course-service.negotiation-type=plaintext

# gRPC Server Configuration
grpc.server.port=5004

# Enrollment Service REST URL
enrollment.service.url=http://enrollment-service:8003
